name: ssh command
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}

      - name: Move to QAMarathon Directory
        run:  cd /app/nao_yoshida

      - name: Print Current Directory
        run: pwd

      - name: Check Directory Existence
        run: ls -a

      - run: ssh ${{ steps.ssh.outputs.SERVER }} bash /app/deploy_test.sh nao_yoshida
