name: ssh command
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} bash /app/deploy.sh nao_yoshida

  deploy_production:
    needs: test
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main' # Only deploy to production on main branch and if tests were successful
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.PRO_SSH_HOST }}
          SSH_PORT: ${{ secrets.PRO_SSH_PORT }}
          SSH_USER: ${{ secrets.PRO_SSH_USER }}
          SSH_KEY: ${{ secrets.PRO_SSHE_SSH_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} bash /app/deploy.sh nao_yoshida